comment:
  image:
    repository: inks/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: inks/post
    tag: latest
    service:
      externalPort: 5000

ui:
  image:
    repository: inks/ui
    tag: latest
    service:
      externalPort: 9292