global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alexey_bogdanov'

