version: '3.3'
services:
  post_db:
    image: mongo:${MONGODB_VERSION}
    volumes:
      - post_db:/data/db
    networks:
#      - reddit
      back_net:
        aliases:
          - comment_db
          - post_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - target: 9292
        published: ${EXTERNAL_PORT}
        protocol: tcp
        mode: host
#      - 9292:9292/tcp
    networks:    
#     - reddit
      - front_net

  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      front_net:
        aliases:
          - post
      back_net:
        aliases:
          - post

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
          - comment

volumes:
  post_db:

networks:
  #   reddit:
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
